# Generated by Django 5.2.8 on 2025-11-14 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practicante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_discord', models.BigIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('semestre', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('en_recuperacion', 'En Recuperación'), ('en_riesgo', 'En Riesgo')], default='activo', max_length=20)),
            ],
            options={
                'verbose_name': 'Practicante',
                'verbose_name_plural': 'Practicantes',
                'db_table': 'practicante',
            },
        ),
    ]
