# Generated by Django 5.2.8 on 2025-11-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance')], default='offline', max_length=20)),
                ('uptime_dias', models.IntegerField(default=0)),
                ('latencia_ms', models.FloatField(default=0.0)),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estado del Bot',
                'verbose_name_plural': 'Estados del Bot',
                'db_table': 'estado_bot',
            },
        ),
        migrations.CreateModel(
            name='MetricasGlobalesBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidores_conectados', models.IntegerField(default=0)),
                ('eventos_procesados_hoy', models.IntegerField(default=0)),
                ('uptime_porcentaje', models.FloatField(default=100.0)),
                ('ultima_sincronizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Métricas Globales del Bot',
                'verbose_name_plural': 'Métricas Globales del Bot',
                'db_table': 'metricas_globales_bot',
            },
        ),
        migrations.CreateModel(
            name='ServidoresBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.BigIntegerField(unique=True)),
                ('server_name', models.CharField(max_length=255)),
                ('miembros', models.IntegerField(default=0)),
                ('canales', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('conectado', 'Conectado'), ('desconectado', 'Desconectado')], default='desconectado', max_length=20)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servidor del Bot',
                'verbose_name_plural': 'Servidores del Bot',
                'db_table': 'servidores_bot',
            },
        ),
    ]
