# Generated by Django 5.2.8 on 2025-12-19 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practicantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado de Asistencia',
                'verbose_name_plural': 'Estados de Asistencia',
                'db_table': 'estado_asistencia',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('practicante', models.ForeignKey(db_column='practicante_id', on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='practicantes.practicante')),
                ('estado', models.ForeignKey(db_column='estado_id', on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='puntualidad.estadoasistencia')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'db_table': 'asistencia',
            },
        ),
        migrations.CreateModel(
            name='HorarioClases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_clase', models.CharField(blank=True, choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], help_text='Día de la semana para clases regulares', max_length=10, null=True)),
                ('dia_recuperacion', models.CharField(blank=True, choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], help_text='Día de la semana para clases de recuperación', max_length=10, null=True)),
                ('practicante', models.ForeignKey(db_column='practicante_id', on_delete=django.db.models.deletion.CASCADE, related_name='horarios_clases', to='practicantes.practicante')),
            ],
            options={
                'verbose_name': 'Horario de Clases',
                'verbose_name_plural': 'Horarios de Clases',
                'db_table': 'horario_clases',
            },
        ),
        migrations.CreateModel(
            name='AsistenciaRecuperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recuperacion', models.DateField()),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20)),
                ('asistencia', models.ForeignKey(db_column='asistencia_id', on_delete=django.db.models.deletion.CASCADE, related_name='recuperaciones', to='puntualidad.asistencia')),
            ],
            options={
                'verbose_name': 'Asistencia de Recuperación',
                'verbose_name_plural': 'Asistencias de Recuperación',
                'db_table': 'asistencia_recuperacion',
                'indexes': [models.Index(fields=['fecha_recuperacion'], name='asistencia__fecha_r_549481_idx'), models.Index(fields=['estado'], name='asistencia__estado_919d35_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['fecha'], name='asistencia_fecha_b120c8_idx'),
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['practicante', 'fecha'], name='asistencia_practic_13da1b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('practicante', 'fecha')},
        ),
    ]
